<a href="https://colab.research.google.com/github/aayushmanz/Python-for-ML/blob/main/Pandas%20in%20Python/Maths%20Methods%20and%20Select%20(cols%2C%20rows%2C%20both)%20in%20DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Math Methods**

In [ ]:
# Sum -> axis arguements

import pandas as pd
import numpy as np

student_dict = {
    'iq' : [80,70,120,80,0,0],
    'marks' : [100,70,100,50,0,0],
    'package' : [10,7,14,2,0,0]
}
std_dict = pd.DataFrame(student_dict)
std_dict.sum()

iq         350
marks      320
package     33
dtype: int64

In [ ]:
# Sum :
std_dict.sum(axis=1)

0    190
1    147
2    234
3    132
4      0
5      0
dtype: int64

In [ ]:
# mean, median, mode
std_dict.mean(axis=1)

0    63.333333
1    49.000000
2    78.000000
3    44.000000
4     0.000000
5     0.000000
dtype: float64

In [ ]:
std_dict.mode(axis=1)

      0      1      2
0  10.0   80.0  100.0
1  70.0    NaN    NaN
2  14.0  100.0  120.0
3   2.0   50.0   80.0
4   0.0    NaN    NaN
5   0.0    NaN    NaN

In [ ]:
std_dict.median(axis=1)

0     80.0
1     70.0
2    100.0
3     50.0
4      0.0
5      0.0
dtype: float64

In [ ]:
# var
std_dict.var(axis=True)

0    2233.333333
1    1323.000000
2    3172.000000
3    1548.000000
4       0.000000
5       0.000000
dtype: float64

**2. Selecting cols in a dataframes :**

In [ ]:
movies = pd.read_csv('/content/movies.csv')
movies.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [ ]:
# single cols :
movies['story'] # single column is series

0       Divided over five chapters  the film chronicle...
1       The story revolves around a cricket match betw...
2       Based on the memoir by Indian policy analyst S...
3       The movie focuses on existing malpractices in ...
4       While gay rights and marriage equality has bee...
                              ...
1624    Raj Dixit lives with his younger brother  Rahu...
1625    Hindi pop-star  Sarina Devan  lives a wealthy ...
1626    Village born Lalloo re-locates to Bombay  and ...
1627    Shinda tries robbing a bank so he can be wealt...
1628    Sara and Ashar are childhood friends who share...
Name: story, Length: 1629, dtype: object

In [22]:
# multiple cols :

movies[['title_x','genres','actors']] # multiple columns is DataFrames

,title_x,genres,actors
0,Uri: The Surgical Strike,Action|Drama|War,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,War,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),Biography|Drama,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,Crime|Drama,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,Drama,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,Drama,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,Drama,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,Comedy|Drama,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,Action,Gippy Grewal|Zareen Khan|
1628,Humsafar,Drama|Romance,Fawad Khan|

**3. Selecting rows in a dataframes :**


*   iloc -> searches using index positions
*   loc -> searches using index labels

In [ ]:
#