<a href="https://colab.research.google.com/github/aayushmanz/Python-for-ML/blob/main/Pandas%20in%20Python/Series%20Indexing%20and%20Slicing%20in%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Series Indexing :-**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# integer Indexing :
x = pd.Series([12,13,14,35,46,57,59,78,9])
x[1]

np.int64(13)

In [ ]:
# negative indexing

x.iloc[-2]

np.int64(78)

In [ ]:
# indexing through numbers
movies = pd.read_csv('/content/bollywood.csv')

movies[0:3]

                                  movie           lead
0              Uri: The Surgical Strike  Vicky Kaushal
1                         Battalion 609    Vicky Ahuja
2  The Accidental Prime Minister (film)    Anupam Kher

In [ ]:
movies[1:5:2]

             movie           lead
1    Battalion 609    Vicky Ahuja
3  Why Cheat India  Emraan Hashmi

In [ ]:
movies = pd.read_csv('/content/bollywood.csv',index_col=['lead'])[0:3]
movies

                                              movie
lead
Vicky Kaushal              Uri: The Surgical Strike
Vicky Ahuja                           Battalion 609
Anupam Kher    The Accidental Prime Minister (film)

In [ ]:

movies.loc['Vicky Ahuja'] # we can also find the data through the charaters iloc()

movie    Battalion 609
Name: Vicky Ahuja, dtype: object

In [ ]:
movies.iloc[0:1] # we can also use iloc() for searching the index

                                  movie
lead
Vicky Kaushal  Uri: The Surgical Strike

In [ ]:
movies.iloc[-1]

movie    The Accidental Prime Minister (film)
Name: Anupam Kher, dtype: object

**Slicing :**

In [ ]:
# slicing :

vk = pd.read_csv('/content/kohli_ipl.csv')

vk[5:16]

    match_no  runs
5          6     9
6          7    34
7          8     0
8          9    21
9         10     3
10        11    10
11        12    38
12        13     3
13        14    11
14        15    50
15        16     2

In [ ]:
# negitive slicing :

vk[-5:]

     match_no  runs
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [ ]:
movies[-5:]

                                              movie
lead
Vicky Kaushal              Uri: The Surgical Strike
Vicky Ahuja                           Battalion 609
Anupam Kher    The Accidental Prime Minister (film)

In [ ]:
movies[::5]

                                  movie
lead
Vicky Kaushal  Uri: The Surgical Strike

In [ ]:
# fancy indexing :

vk.iloc[[1,3,4,5]]

   match_no  runs
1         2    23
3         4    12
4         5     1
5         6     9

In [ ]:
# indexing with labels -> fancy indexing
movies.loc['Vicky Ahuja']

movie    Battalion 609
Name: Vicky Ahuja, dtype: object