<a href="https://colab.research.google.com/github/aayushmanz/Python-for-ML/blob/Colab/series_in_pandas_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Series Using read_csv() :**

In [ ]:
import pandas as pd

# with one col :
# Squeeze=True is not working in the latest Pandas version.
pd.read_csv('/content/ipl-matches.csv')['Team1']

0                 Rajasthan Royals
1      Royal Challengers Bangalore
2      Royal Challengers Bangalore
3                 Rajasthan Royals
4              Sunrisers Hyderabad
                  ...
945          Kolkata Knight Riders
946                 Mumbai Indians
947               Delhi Daredevils
948                Kings XI Punjab
949    Royal Challengers Bangalore
Name: Team1, Length: 950, dtype: object

In [ ]:
# with 2 cols :

matches = pd.read_csv('/content/batsman_runs_ipl.csv', index_col=['batter', 'batsman_run'])

matches

Empty DataFrame
Columns: []
Index: [(A Ashish Reddy, 280), (A Badoni, 161), (A Chandila, 4), (A Chopra, 53), (A Choudhary, 25), (A Dananjaya, 4), (A Flintoff, 62), (A Kumble, 35), (A Manohar, 108), (A Mishra, 362), (A Mithun, 34), (A Mukund, 19), (A Nehra, 41), (A Nortje, 8), (A Singh, 2), (A Symonds, 974), (A Tomar, 4), (A Uniyal, 4), (A Zampa, 5), (AA Bilakhia, 69), (AA Chavan, 12), (AA Jhunjhunwala, 217), (AA Noffke, 9), (AB Agarkar, 179), (AB Barath, 42), (AB Dinda, 26), (AB McDonald, 123), (AB de Villiers, 5181), (AC Blizzard, 120), (AC Gilchrist, 2069), (AC Thomas, 20), (AC Voges, 181), (AD Hales, 148), (AD Mascarenhas, 79), (AD Mathews, 724), (AD Nath, 90), (AD Russell, 2039), (AF Milne, 23), (AG Murtaza, 10), (AG Paunikar, 49), (AJ Finch, 2092), (AJ Turner, 3), (AJ Tye, 91), (AK Markram, 527), (AL Menaria, 401), (AM Nayar, 672), (AM Rahane, 4074), (AN Ahmed, 36), (AN Ghosh, 7), (AP Dole, 34), (AP Majumdar, 87), (AP Tare, 339), (AR Bawne, 12), (AR Patel, 1135), (AS Joseph, 20), (AS Rajpoot, 26), (AS Raut, 194), (AS Roy, 0), (AS Yadav, 49), (AT Carey, 32), (AT Rayudu, 4190), (AUK Pathan, 39), (Abdul Samad, 228), (Abdur Razzak, 0), (Abhishek Sharma, 667), (Akash Deep, 0), (Aman Hakim Khan, 5), (Anirudh Singh, 63), (Ankit Sharma, 87), (Ankit Soni, 7), (Anmolpreet Singh, 29), (Anuj Rawat, 129), (Anureet Singh, 36), (Arshdeep Singh, 23), (Avesh Khan, 31), (Azhar Mahmood, 388), (B Akhil, 76), (B Chipli, 280), (B Indrajith, 21), (B Kumar, 241), (B Laughlin, 5), (B Lee, 124), (B Sai Sudharsan, 145), (B Stanlake, 5), (B Sumanth, 35), (BA Bhatt, 6), (BA Stokes, 920), (BAW Mendis, 3), (BB McCullum, 2882), (BB Samantray, 125), (BB Sran, 10), (BCJ Cutting, 238), (BE Hendricks, 1), (BJ Haddin, 18), (BJ Hodge, 1400), (BJ Rohrer, 193), (BMAJ Mendis, 23), (BR Dunk, 40), (Basil Thampi, 32), (Bipul Sharma, 187), ...]

[605 rows x 0 columns]

In [ ]:
# Example :

pd.read_csv("/content/diabetes.csv", index_col=['BloodPressure'])['Age']

BloodPressure
72    50
66    31
64    32
66    21
40    33
      ..
76    63
70    27
72    30
60    47
70    23
Name: Age, Length: 768, dtype: int64