<a href="https://colab.research.google.com/github/aayushmanz/Python-for-ML/blob/colab/Series%20Maths%20Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Series Maths Methods :**

In [2]:
import pandas as pd
import numpy as np

vk = pd.read_csv("/content/kohli_ipl.csv")
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [6]:
# count :
vk.count()

match_no    215
runs        215
dtype: int64

In [8]:
# Sum -> Product

subs = pd.read_csv("/content/subs.csv")

subs.sum()

Subscribers gained    49510
dtype: int64

In [11]:
subs.product()

Subscribers gained    0
dtype: int64

In [12]:
# Means -> median -> mode -> std -> var

subs.mean()

Subscribers gained    135.643836
dtype: float64

In [13]:
print(vk.median())

match_no    108.0
runs         24.0
dtype: float64

In [17]:
movies = pd.read_csv("/content/bollywood.csv")['lead']
print(movies.mode())

1

In [18]:
subs.std()

Subscribers gained    62.675023
dtype: float64

In [19]:
vk.var()

match_no    3870.000000
runs         688.002478
dtype: float64

In [20]:
# Min / max :

subs.max() # Max subscibers count day !

Subscribers gained    396
dtype: int64

In [21]:
subs.min() # Min subscibers count day !

Subscribers gained    33
dtype: int64

In [23]:
# describe :

print(vk.describe()) # mathmetical summary

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000