In [2]:
import pandas as pd
import numpy as np

city_gdp = pd.read_csv('/workspaces/Python-for-ML/Database from Kaggle/cities_by_gdp.csv')

In [3]:
city_gdp.head(2)

,Index,Metropolitian Area/City,Country/Region,Official est. GDP(billion US$),Metropolitian Population
0,1,A Coruña metropolitan area,Spain,28.819,"1,121,815"
1,2,Aachen,Germany,24.296,"249,070"

In [4]:
# Show only indian cities data  :

city_gdp[city_gdp['Country/Region']=='India']

,Index,Metropolitian Area/City,Country/Region,Official est. GDP(billion US$),Metropolitian Population
10,11,Ahmedabad,India,80,"9,300,000"
75,76,Bengaluru,India,110,"13,200,000"
78,79,Bhopal,India,5.35,"2,600,000"
145,146,Chandigarh,India,6,"2,575,000"
157,158,Chennai,India,128.3,"12,200,000"
172,173,Coimbatore,India,42,"2,775,000"
360,361,Hyderabad,India,74,"9,482,000"
364,365,Indore,India,8.1,"3,175,000"
376,377,Jaipur,India,15,"4,050,000"
420,421,Kolkata,India,160.2,"17,200,000"
481,482,Lucknow,India,3.83,"4,000,000"
548,549,Mumbai,India,277.98,"22,300,000"
555,556,Nagpur,India,19,"3,127,000"
567,568,National Capital Region (Delhi),India,272.603,"31,300,000"
619,620,Patna,India,30,"2,800,000"
650,651,Pune,India,69,"9,429,408"
774,775,Surat,India,59.8,"6,600,000"
838,839,Vishakhapatnam,India,43.5,"2,200,000"

In [5]:
# find those cities which have more than 50 billion dollar gdp.
city_gdp["Official est. GDP(billion US$)"] = pd.to_numeric(city_gdp["Official est. GDP(billion US$)"],errors='coerce')
city_gdp[city_gdp["Official est. GDP(billion US$)"].notnull()].count()

Index                             899
Metropolitian Area/City           899
Country/Region                    899
Official est. GDP(billion US$)    899
Metropolitian Population          899
dtype: int64

In [6]:
city_gdp["Official est. GDP(billion US$)"].dropna( inplace=True)

In [7]:
city_is_cleaned = city_gdp[city_gdp["Official est. GDP(billion US$)"]>50.0]
city_is_cleaned.sort_values(by="Official est. GDP(billion US$)",ascending=False)

,Index,Metropolitian Area/City,Country/Region,Official est. GDP(billion US$),Metropolitian Population
472,473,London metropolitan area,United Kingdom,978.402,"14,800,000"
616,617,Paris metropolitan area,France,934.168,"14,800,000"
730,731,Seoul Capital Area,South Korea,878.535,"24,800,000"
159,160,"Chicago–Naperville, IL–IN–WI CSA",United States,832.899,"9,806,184"
429,430,Kyoto–Osaka–Kobe,Japan,699.474,"17,700,000"
...,...,...,...,...,...
370,371,İzmir,Turkey,51.460,"3,050,000"
595,596,Ordos,China,51.232,"2,153,638"
215,216,Dresden,Germany,50.788,"1,343,747"
192,193,Daegu,South Korea,50.400,"2,750,000"
877,878,Xuchang,China,50.008,"4,379,998"

In [8]:
city_is_cleaned.count()

Index                             262
Metropolitian Area/City           262
Country/Region                    262
Official est. GDP(billion US$)    262
Metropolitian Population          262
dtype: int64

In [9]:
# find the cities with highest number of population with more than 10 lakh.

city_gdp.head(2)
city_gdp['Metropolitian Population'].info() # now we know that our data is str

<class 'pandas.Series'>
RangeIndex: 903 entries, 0 to 902
Series name: Metropolitian Population
Non-Null Count  Dtype
--------------  -----
903 non-null    str
dtypes: str(1)
memory usage: 7.2 KB

In [10]:
city_gdp = pd.read_csv('/workspaces/Python-for-ML/Database from Kaggle/cities_by_gdp.csv')

In [11]:
city_gdp['Metropolitian Population'] = city_gdp['Metropolitian Population'].str.replace(',','')
city_gdp['Metropolitian Population'] = pd.to_numeric(city_gdp['Metropolitian Population'], errors='coerce')

In [12]:
most_popu_city = city_gdp[city_gdp['Metropolitian Population']>1000000]
most_popu_city.sort_values(by='Metropolitian Population',ascending=False).head()

,Index,Metropolitian Area/City,Country/Region,Official est. GDP(billion US$),Metropolitian Population
300,301,Greater Tokyo Area,Japan,"2,080.758",40700000.0
377,378,Jakarta metropolitan area,Indonesia,323.030,34307088.0
567,568,National Capital Region (Delhi),India,272.603,31300000.0
295,296,Greater Manila Area,Philippines,162.3,26400000.0
732,733,Shanghai,China,663.874,24890106.0

In [13]:
# sort the gdp in descending order.
city = pd.read_csv('/workspaces/Python-for-ML/Database from Kaggle/cities_by_gdp.csv')
city['Official est. GDP(billion US$)'] = pd.to_numeric(city['Official est. GDP(billion US$)'], errors='coerce')
city.sort_values(by='Official est. GDP(billion US$)',ascending=False).head()

,Index,Metropolitian Area/City,Country/Region,Official est. GDP(billion US$),Metropolitian Population
472,473,London metropolitan area,United Kingdom,978.402,"14,800,000"
616,617,Paris metropolitan area,France,934.168,"14,800,000"
730,731,Seoul Capital Area,South Korea,878.535,"24,800,000"
159,160,"Chicago–Naperville, IL–IN–WI CSA",United States,832.899,"9,806,184"
429,430,Kyoto–Osaka–Kobe,Japan,699.474,"17,700,000"