In [1]:
import pandas as pd
import numpy as np

std = pd.read_csv('/workspaces/Python-for-ML/Database from Kaggle/student_performance_finalscore.csv')
std.sample(5)

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Final_Score
3883,STU03884,18,Female,5.01,79.6,6.4,5.7,4.4,3.24,Yes,Offline,Average,Good,No,2,Low,3.7,85.74
2452,STU02453,23,Male,5.91,77.0,5.8,4.4,5.1,2.52,No,Offline,Average,Average,No,1,Middle,5.4,82.52
2472,STU02473,23,Female,2.32,79.4,7.9,3.3,3.9,2.16,Yes,Hybrid,Poor,Average,Yes,0,High,6.2,41.68
4331,STU04332,22,Female,5.07,99.3,7.4,5.5,3.7,2.27,Yes,Hybrid,Average,Average,No,1,High,6.6,80.00
5905,STU05906,23,Female,8.44,95.2,8.5,6.5,3.1,3.14,Yes,Online,Average,Average,Yes,1,Middle,3.4,85.09

In [2]:
std['Student_ID'].count() # finding total students

np.int64(8000)

In [3]:
# total Non-binary students who are eligible of exams
std[(std['Attendance']>75)&(std['Gender']=="Non-Binary")].count()
std[(std['Attendance'] > 75) & (std['Gender'] == "Non-Binary") & (std['Study_Method'] == "Offline")].shape[0]

61

In [55]:
# What is the average Final_Score and Previous_GPA of all the students in this dataset?

std_data = pd.read_csv("/workspaces/Python-for-ML/Database from Kaggle/student_performance_finalscore.csv")
std_data.sample(3)

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Final_Score
3789,STU03790,19,Female,7.08,96.9,8.7,6.4,3.7,2.33,No,Offline,Average,Average,Yes,0,High,2.9,93.95
7891,STU07892,18,Male,5.32,74.5,6.5,3.9,3.1,3.89,No,Offline,Average,Good,Yes,0,Middle,4.3,89.98
5793,STU05794,18,Male,4.12,68.9,6.5,3.1,2.1,2.62,No,Online,Average,Average,Yes,3,Middle,3.7,84.65

In [17]:
avg_previous = std_data['Previous_GPA'].mean()
avg_final = std_data['Final_Score'].mean()
print("The Final Year Average : " , avg_final)
print(f'The Previous Year Average : {avg_previous}')

The Final Year Average :  83.20564875
The Previous Year Average : 2.9924075

In [ ]:
# Which age group has the highest representation in the Age column?
std_data.sample()

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Final_Score,Average_Previous_GPA
4241,STU04242,24,Male,4.22,64.2,6.7,5.4,2.8,2.87,Yes,Online,Good,Average,Yes,0,Low,3.5,77.95,2.992408

In [34]:
std_data.groupby("Age")['Age'].count().sort_values(ascending=False)

Age
18    1022
21    1016
23    1009
20     996
19     994
22     993
17     988
24     982
Name: Age, dtype: int64

In [53]:
# Out of the available Study_Method options (Online, Offline, Hybrid), which one is most preferred by the students?
data = std_data.groupby("Study_Method")['Study_Method'].count().sort_values(ascending=False)
print("There are most of studnet Enrolled in : ",data.index[0])
print(f'Total Number of Studnets with {data.index[0]} is {data.iloc[0]}')

There are most of studnet Enrolled in :  Offline
Total Number of Studnets with Offline is 3170

In [57]:
# Does an increase in Hours_Studied actually result in a higher Final_Score?
std_data.sample(6)

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Final_Score
7767,STU07768,19,Female,4.30,75.9,5.0,6.0,1.8,2.69,No,Hybrid,Poor,Good,No,3,Middle,3.8,71.36
4477,STU04478,24,Female,6.30,67.6,6.4,4.6,5.6,2.39,No,Online,Good,Good,Yes,1,Middle,7.0,93.01
5475,STU05476,21,Female,5.47,81.4,7.2,3.4,3.1,2.88,Yes,Hybrid,Poor,Good,Yes,3,Middle,4.3,90.28
1844,STU01845,24,Male,6.37,89.9,6.5,3.6,3.6,2.87,Yes,Offline,Good,Average,Yes,1,High,2.0,99.16
3590,STU03591,18,Female,4.28,87.3,4.2,4.5,3.1,2.94,No,Offline,Average,Good,No,3,Middle,4.5,86.44
4016,STU04017,24,Male,4.70,95.8,8.1,4.0,4.2,2.06,No,Online,Good,Good,Yes,3,High,6.5,64.04

In [74]:
corrilation = std_data['Hours_Studied'].corr(std_data['Final_Score'])
print(corrilation.astype('float32'))

0.5913555

In [85]:
# Do students who maintain more than 80% Attendance score significantly better than the rest of the class?
high = std_data[std_data["Attendance"]>80.0]['Final_Score'].mean()
low =std_data[std_data['Final_Score']<=80.0]['Final_Score'].mean()

print(f'The High attendance std score : {high:.2f}')
print(f'The Lower attendance std score : {low:.2f}')

The High attendance std score : 84.90
The Lower attendance std score : 68.23

In [104]:
# Is there a direct link between Exam_Anxiety_Score and Stress_Level? Do students with high stress end up getting lower marks?
a = std_data['Exam_Anxiety_Score'].corr(std_data['Final_Score'])
b = std_data['Stress_Level'].corr(std_data['Final_Score'])

print(f"The Answer for Exam_Anxiety_Score Student final Studnet : {a:.2f} ")
print(f"The Answer for Stress_Level Student final Studnet : {b:.2f} ")

The Answer for Exam_Anxiety_Score Student final Studnet : -0.49
The Answer for Stress_Level Student final Studnet : -0.30

np.float64(79.933375)