<a href="https://colab.research.google.com/github/aayushmanz/Python-for-ML/blob/main/Pandas%20in%20Python/Editing%20index%20%2C%20Python%20Functionality%20in%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Editing Series :

In [2]:
import pandas as pd
import numpy as np

marks_series = {
    "English" : 67,
    "Hindi"   : 78,
    "Science" : 89,
    "Maths"   : 90
}

marks = pd.Series(marks_series, name="Ayush Suthar")
print(marks)

English    67
Hindi      78
Science    89
Maths      90
Name: Ayush Suthar, dtype: int64

In [5]:
# using indexing :
marks[1] = 100
print(marks)

English     67
Hindi      100
Science     89
Maths       90
Name: Ayush Suthar, dtype: int64

/tmp/ipykernel_1520/3033967775.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks[1] = 100

In [48]:
marks['Hindi'] = 99
print(marks)

English    67
Hindi      99
Science    89
Maths      90
Social     78
Name: Ayush Suthar, dtype: int64

In [49]:
marks[1:1] = 99
print(marks)

English    67
Hindi      99
Science    89
Maths      90
Social     78
Name: Ayush Suthar, dtype: int64

In [7]:
# what if an index does not exist
marks['Social'] = 78

marks

English     67
Hindi      100
Science     89
Maths       90
Social      78
Name: Ayush Suthar, dtype: int64

In [12]:
# slicing :

runs = pd.read_csv("/content/kohli_ipl.csv").head()['runs']

runs

0     1
1    23
2    13
3    12
4     1
Name: runs, dtype: int64

In [14]:
runs[1:3] = [100,100]

runs

0      1
1    100
2    100
3     12
4      1
Name: runs, dtype: int64

In [17]:
# fancy index label
runs[[0,3,4]] = [0,0,0]

runs

0      0
1    100
2    100
3      0
4      0
Name: runs, dtype: int64

In [87]:
# using index label

movies = pd.read_csv("/content/bollywood.csv").head()

movies

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [75]:
movies.loc['Why Cheat India'] = 'Ayush Suthar'
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                           Ayush Suthar
Evening Shadows                       Mona Ambegaonkar

# Series with Python Functionalities :

**1. len/type/dir/sorted/max/min**

In [58]:

# len()

print(len(marks))

5

In [59]:
# type()

print(type(marks))

<class 'pandas.core.series.Series'>

In [60]:
# dir()

print(dir(marks))

['English', 'Hindi', 'Maths', 'Science', 'Social', 'T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']

In [61]:
# sorted()

print(sorted(marks))

[67, 78, 89, 90, 99]

In [62]:
# max()

print(max(marks))

99

In [63]:
# min()

print(min(marks))

67

**2. Type conversion**

In [64]:
list(marks)

[67, 99, 89, 90, 78]

In [65]:
dict(marks)

{'English': np.int64(67),
 'Hindi': np.int64(99),
 'Science': np.int64(89),
 'Maths': np.int64(90),
 'Social': np.int64(78)}

**3. membership operator**

In [82]:
'lead' in movies # column name we can find

True

In [85]:
'Anupam Kher' in movies.values

True

**4. looping**

In [100]:
movies = pd.read_csv("/content/bollywood.csv").head(10)

movies

                                  movie                  lead
0              Uri: The Surgical Strike         Vicky Kaushal
1                         Battalion 609           Vicky Ahuja
2  The Accidental Prime Minister (film)           Anupam Kher
3                       Why Cheat India         Emraan Hashmi
4                       Evening Shadows      Mona Ambegaonkar
5                           Soni (film)  Geetika Vidya Ohlyan
6                         Fraud Saiyaan          Arshad Warsi
7                            Bombairiya          Radhika Apte
8      Manikarnika: The Queen of Jhansi        Kangana Ranaut
9                      Thackeray (film)   Nawazuddin Siddiqui

In [105]:
for i in movies : # for columns
  print(i)

movie
lead

In [102]:
for i in movies.index :  # for index
  print(i)

0
1
2
3
4
5
6
7
8
9

In [103]:
for i in movies.values : # for values
  print(i)

['Uri: The Surgical Strike' 'Vicky Kaushal']
['Battalion 609' 'Vicky Ahuja']
['The Accidental Prime Minister (film)' 'Anupam Kher']
['Why Cheat India' 'Emraan Hashmi']
['Evening Shadows' 'Mona Ambegaonkar']
['Soni (film)' 'Geetika Vidya Ohlyan']
['Fraud Saiyaan' 'Arshad Warsi']
['Bombairiya' 'Radhika Apte']
['Manikarnika: The Queen of Jhansi' 'Kangana Ranaut']
['Thackeray (film)' 'Nawazuddin Siddiqui']

In [110]:
for i in movies['movie'] : # for the index values
  print(i)

Uri: The Surgical Strike
Battalion 609
The Accidental Prime Minister (film)
Why Cheat India
Evening Shadows
Soni (film)
Fraud Saiyaan
Bombairiya
Manikarnika: The Queen of Jhansi
Thackeray (film)

In [111]:
for i in movies['lead'] : # for index values
  print(i)

Vicky Kaushal
Vicky Ahuja
Anupam Kher
Emraan Hashmi
Mona Ambegaonkar
Geetika Vidya Ohlyan
Arshad Warsi
Radhika Apte
Kangana Ranaut
Nawazuddin Siddiqui

**5. Arithmetic Operations (Broadcasting)**

In [113]:
100 + marks # adding 100 with all values

English    167
Hindi      199
Science    189
Maths      190
Social     178
Name: Ayush Suthar, dtype: int64

**6. Relational Operations :**

In [114]:
runs >= 50

0    False
1     True
2     True
3    False
4    False
Name: runs, dtype: bool

# Boolean Indexing on Series :

In [124]:
vk = pd.read_csv("/content/kohli_ipl.csv")

vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [121]:
# find no of 50's and 100's scored by kohli :

vk[vk['runs'] >= 30].size

6

In [125]:
# find number of ducks

vk[vk['runs']==0]

     match_no  runs
7           8     0
86         87     0
90         91     0
92         93     0
129       130     0
134       135     0
205       206     0
206       207     0
210       211     0

In [126]:
vk[vk['runs']==0].size

18

In [132]:
# count number of day when I had more than 200 subs a day
subs = pd.read_csv("/content/subs.csv")

subs[subs['Subscribers gained'] > 200]

     Subscribers gained
165                 225
166                 249
167                 265
168                 306
169                 261
170                 222
225                 224
226                 254
227                 214
228                 236
229                 261
230                 247
231                 207
232                 254
233                 301
234                 233
240                 202
246                 259
248                 213
249                 210
252                 216
275                 228
276                 237
277                 276
279                 290
280                 295
281                 245
282                 241
283                 267
284                 269
285                 211
287                 206
288                 202
290                 236
291                 222
292                 203
312                 230
318                 244
324                 243
325                 227
326                 259
330                 396
331                 312
332                 268
333                 229
337                 221
338                 225
339                 221
340                 202
344                 276
345                 258
346                 219
347                 212
351                 220
354                 204
358                 210
359                 209
360                 231
361                 226

In [133]:
subs[subs['Subscribers gained'] > 200].size

59

In [144]:
# find actors who have done more than 20 movies.

movies = pd.read_csv("/content/bollywood.csv")

num_movie = movies['lead'].value_counts()
print(num_movie[num_movie > 20])

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64